# Generated by Django 5.0.6 on 2024-06-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
    ]
