# Generated by Django 5.0.6 on 2024-07-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('subscribed_on', models.DateTimeField(null=True)),
                ('expiring_on', models.DateTimeField(null=True)),
                ('subscription_period', models.CharField(choices=[('mn', 'monthly'), ('qt', 'quaterly'), ('hf', 'half_yearly'), ('yr', 'anually')], max_length=255)),
                ('is_notificated', models.BooleanField(default=False)),
                ('service_chosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premium.serviceproduct')),
            ],
        ),
    ]
