# Generated by Django 5.0.6 on 2024-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_notificated',
            field=models.BooleanField(default=False),
        ),
    ]
